# Generated by Django 3.0.2 on 2020-02-04 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='app_data_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='app_user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Products_Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22)),
                ('total_quantity', models.IntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22)),
                ('app_user_id', models.CharField(max_length=200, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Products')),
            ],
        ),
    ]
