# Generated by Django 3.0.2 on 2020-02-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200204_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
