# Generated by Django 3.0.2 on 2020-02-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_products_total_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Photo_Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=15)),
                ('document_type', models.CharField(choices=[('', 'Select'), ('P', 'Photo'), ('S', 'Signature Card')], default='', max_length=2)),
                ('document_location', models.ImageField(upload_to='sign_image/')),
                ('app_user_id', models.IntegerField(blank=True, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
